//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRUBookShop64
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBookType
    {
        public int BookTypeID { get; set; }
        public string BookTypeName { get; set; }
    }
}
