//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRUBookShop64
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSaleDetail
    {
        public int ID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
