//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRUBookShop64
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSale
    {
        public int SaleID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> TotalAmount { get; set; }
    }
}
