//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRUBookShop64
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VRUBookShop : DbContext
    {
        public VRUBookShop()
            : base("name=VRUBookShop")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbBooks> tbBooks { get; set; }
        public virtual DbSet<tbBookType> tbBookType { get; set; }
        public virtual DbSet<tbSale> tbSale { get; set; }
        public virtual DbSet<tbSaleDetail> tbSaleDetail { get; set; }
    }
}
